[package]
name = "bly"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
raw-window-handle = "0.5.0"

log = "0.4.17"
env_logger = "0.10.0"

bly-ac = { path = "../bly-ac" }

[target."cfg(windows)".dependencies]
bly-dx2d = { path = "../bly-dx2d" }

[dev-dependencies]
winit = "0.28.1"